name: Build
on:
  push:

permissions:
  contents: read

jobs:
  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.25.0"
          cache: false
      - name: Run spellcheck
        run: |
          go install github.com/client9/misspell/cmd/misspell@latest
          misspell -error docs
