name: Build
on:
  push:

permissions:
  contents: read

jobs:
  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.25.0"
          cache: false
      - name: Run spellcheck
        run: |
          go install github.com/client9/misspell/cmd/misspell@latest
          misspell -error docs

  markdown-lint:
    name: Markdown Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint Markdown
        uses: DavidAnson/markdownlint-cli2-action@v15
        with:
          globs: 'docs/**/*.md'
